### ISSUE TITLE
LDAP Injection

### ISSUE THREAD

**Issue by curea** [pumasecurity/puma-scan#1]
Look for dynamic values being created appended into LDAP filters or DN's. Examples below:

Filters:
DirectoryEntry.Filter = <bad data>

OR

DN's:
DirectoryEntr de = new DirectoryEntry("LDAP://yourserver/CN=Users,dc=<bad data>,dc=com");

**Comment by meadisu27** [comment]
DirectorySearcher.Filter = ...
or
var searcher = new DirectorySearcher(root, **filter**)

**Comment by ejohn20** [comment]
Forgot to mention this. The solution here is to use the Encoder.LdapFilterEncode method to escape bad things.

**Comment by ejohn20** [comment]
Similarly, Encoder.LdapDistinguishedNameEncode() method. Both are in the AntiXSS (WPL) lib.
