### ISSUE TITLE
Disabling Certificate Validation

### ISSUE THREAD

**Issue by curea** [pumasecurity/puma-scan#13]
String url = "https://www.stackoverflow.com";
HttpWebRequest request = HttpWebRequest.CreateHttp(url);
request.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => { return true; };

OR

ServicePointManager.ServerCertificateValidationCallback +=
    (sender, cert, chain, sslPolicyErrors) => true;

OR

using (var handler = new WebRequestHandler())
{
    handler.ServerCertificateValidationCallback +=  (sender, cert, chain, sslPolicyErrors) => true;

    using (var client = new HttpClient(handler))
    {
    }
}

**Comment by ejohn20** [comment]
Added by @meadisu27 in v 1.0.2
