### ISSUE TITLE
Analyze Code via .NET Core Docker File

### ISSUE THREAD

**Issue by chadbrewbaker** [pumasecurity/puma-scan#20]
400+ errors when the project is opened in Visual Studio for Mac Preview 1. Looks like a lot of them have to do with Visual Studio integration, not Roslyn. Will try to go through them.

**Comment by ejohn20** [comment]
Yikes! It definitely has not been tested over on VS for Mac yet. Might be worth playing with a bit to see if it is possible in that IDE at some point.

**Comment by meadisu27** [comment]
Watch MS connect conference yesterday. VS for mac only supports .net core.

**Comment by ejohn20** [comment]
Ah, that would explain it. We have libs in use that are not in .NET core. We'd need to fork a version for core, which isn't a bad idea anyway going forward.

**Comment by ejohn20** [comment]
To my knowledge, this is still not possible. Let me know if I'm wrong.

**Comment by chadbrewbaker** [comment]
https://github.com/lambci/docker-lambda/blob/master/dotnetcore2.1/build/Dockerfile

I'd load up that Docker container and annotate this thread with what breaks when you install/run Puma headless tooling.  Ideally it would be nice to add to this Docker file so Puma can run in anybody's CI pipeline without a Windows dependency.

**Comment by ejohn20** [comment]
Closing this issue. Scans are working inside the Docker container and from standard "dotnet build" commands. See wiki for details. https://github.com/pumasecurity/puma-scan/wiki/Puma-Scan-Hunting
