### ISSUE TITLE
Set NuGet Package as DevelopmentDependency

### ISSUE THREAD

**Issue by kyleherzog** [pumasecurity/puma-scan#27]
The PumaScan NuGet package should set itself as a development dependency, as it is a dependency that is only useful for development and should not be required by other packages by default.  This can be done by adding the following to the .nuspec file.
```xml
<developmentDependency>true</developmentDependency>
```

**Comment by ejohn20** [comment]
Sounds simple enough. Adding this to the next release. Does this have any downstream effects on the rules running during MSBuild?

**Comment by kyleherzog** [comment]
Personally, I haven't experienced any impact to the MSBuild process by adding this setting.

**Comment by ejohn20** [comment]
Released.
