### ISSUE TITLE
Rule Options Screen

### ISSUE THREAD

**Issue by curea** [pumasecurity/puma-scan#4]
Currently, the RuleOptions.cs file contains some hard-coded values that drives some of the rules (auth timeout, password complexity, etc.)

This needs to be editable via a configuration screen in IDE. Something like Tools > Options > Puma Scan > General. This could produce a ruleoptions.json file if we want it to.

For the NuGet package, this can be done via a ruleoptions.json file with the same configuration values.

Each rule should have an enabled / disabled flag that selects which rules run. Any rules that are taint oriented should have a list of vulnerable sinks and sources that can be configured within the rule, each one having its own enabled flag as well.

**Comment by ejohn20** [comment]
Cancelling this item. As this is open source, folks can fork and customize their sinks / config values on their own.
