### ISSUE TITLE
Eternal loop in GetParentLocalDeclarationStatement

### ISSUE THREAD

**Issue by JarLob** [pumasecurity/puma-scan#40]
It might be the cause of https://github.com/pumasecurity/puma-scan/issues/39 because I found it running the same project. 
There is no `break` at the end of `while(true)` in `GetParentLocalDeclarationStatement` as it is in `SymbolInheritsFrom`. This causes an eternal loop when an item is not `null`, not `LocalDeclarationStatementSyntax` and doesn't have a parent.

May I suggest also adding something similar to snippet below to prevent it in the future:
```
var analyzeTask = AnalyzeAsync();
var timeoutTask = Task.Delay(10000);
var completedTask = await Task.WhenAny(analyzeTask, timeoutTask);
if (completedTask == timeoutTask)
    throw new TimeoutException();
```

**Comment by ejohn20** [comment]
@JarLob awesome find. I'll tinker with this and see if it resolves the issue. 

@meadisu27 Do you know if this is corrected in the latest version about to be pushed?

**Comment by meadisu27** [comment]
@ejohn20 No I don't believe it is. The release candidate still needs the VS2015 combatibility issues merged in. Can squeeze this in as well.

**Comment by ejohn20** [comment]
I'm debugging this now. Definitely was the root of the issue. I'm going to put a check in the loop to prevent it at that layer. I also like the idea of a timeout as @JarLob describes above to prevent the analyzers from hosing up the build as well.

**Comment by ejohn20** [comment]
OK - patch fix in flight. This will be in the 2.x version of the open source package to be released shortly.

**Comment by ejohn20** [comment]
Deployed in 1.0.7 release this morning.
