### ISSUE TITLE
VB code scan

### ISSUE THREAD

**Issue by hemanthnalluri** [pumasecurity/puma-scan#42]
Hi,

can Puma will analyse the project which is written in Vb coding.
i am using VS 2015 

First i've written the code in C# then puma scanner is showing the vulnerability error

Severity	Code	Description	Project	File	Line	Suppression State
Warning	SEC0110	Unvalidated redirect location is passed to the Response.Redirect method.	Sample1	C:\Users\KDDuser\Desktop\Sample1\Sample1\Account\Register.aspx.cs	28	Active
Warning	SEC0107	SQL Injection - ADO.NET method is passed a dynamic SQL statement.	Sample1	C:\Users\KDDuser\Desktop\Sample1\Sample1\Register.aspx.cs	45	Active

 i've written the code in VB it was not showing any vulnerability error

so can you please conform can puma scanner will analyse the Vb written code.

if yes please let me know steps to check why it is not scanning the Vb code.

Thanks,
Hemanth.

**Comment by ejohn20** [comment]
Right now, the rules do not support VB.NET. Only C# is supported. There is a possibility Roslyn is going to sync up both C# and VB.NET syntax types in a future release, but to my knowledge this is not available yet.

**Comment by hemanthnalluri** [comment]
ok noted thanks.
