### ISSUE TITLE
Which version of Visual Studio does Puma Scan support?

### ISSUE THREAD

**Issue by YeeSuan95** [pumasecurity/puma-scan#47]
Few months ago, I was using Puma Scan in Visual Studio 2015. However, it seem like it only support in Visual Studio 2017 now. Does it not support in Visual Studio 2015 anymore??

**Comment by ejohn20** [comment]
The latest version (2.0.0.1) upgraded the Roslyn libraries to gain additional analysis capabilities. However, these libraries only work in Visual Studio 2017 15.8+.

The previous version (1.0.7) is still available for older versions of Visual Studio on the project releases page.

https://github.com/pumasecurity/puma-scan/releases
