### ISSUE TITLE
Version 1.0.7 does not prompt any warnings 

### ISSUE THREAD

**Issue by YeeSuan95** [pumasecurity/puma-scan#48]
Hi, 

I'm using Puma Scan Version 1.0.7 in VS 2015 mainly. It does not prompt any warnings in my error list panel. However, it prompted errors in VS 2017 when i'm using version 2.0.0.1. It does not tally with VS 2015. Is it Cos' version 1.0.7 is depreciating?? If so, is there no fixes for it?

Thanks.

**Comment by ejohn20** [comment]
Version 1.0.7 should work for VS2015. Did you enable full solution analysis? If so, can you provide more details on what diagnostic is not showing up?

**Comment by YeeSuan95** [comment]
Yes, i did enabled the full solution analysis.
Example of diagnostic that does not work such as **"Unvalidated redirect location is passed to the Response.Redirect method"** and **"Unvalidated file paths are passed to a file open API, which can allow unauthorized file system operations (e.g. read, write, delete) to be performed on unintended server files."**

**Comment by ejohn20** [comment]
Please provide code snippets of the warnings that are not showing. These rules are supposed in the 1.0.7 version.

**Comment by YeeSuan95** [comment]
![image](https://user-images.githubusercontent.com/8421108/46326820-4d74d680-c631-11e8-8306-af87d46c7fa8.png)

The previous comment are the warnings that are not appearing in VS 2015, while it appeared only in VS 2017 for my program. 

Do take note once again. For VS 2015, i'm using 1.0.7 while in VS 2017, i'm using 2.0.0.1.

**Comment by ejohn20** [comment]
@YeeSuan95 In Visual Studio 2015 are you seeing the spell check warnings on the actual line of code in the document?

**Comment by ejohn20** [comment]
Closing this issue. VS2015 is not supported with newer versions of the extension. We recommend upgrading to VS2017.
