### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by xperiandri** [pumasecurity/puma-scan#52]
https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by ejohn20** [comment]
We'll add support for this when it comes out of preview.

**Comment by DavidColemanUK** [comment]
Hi, is 2019 support available now that it's out of Preview and into RC?

**Comment by ejohn20** [comment]
I've got this in the netstandard branch along with some other changes. If a release a preview vsix package, are you willing to test it for me in 2019 and report back?

**Comment by IgorMilavec** [comment]
I can test it on a couple of projects, some migrated to C# 8 and some still on 7.x.

**Comment by ejohn20** [comment]
Just published a preview release with support for 2019: https://github.com/pumasecurity/puma-scan/releases

Let us know how it goes!

**Comment by IgorMilavec** [comment]
I have tested with 2019 RC4 and had no problems with either installation or analysis this far.
I will report if anything pops up!

**Comment by ejohn20** [comment]
Perfect, let me know if anything pops up. I've got a few tweaks I need to add to the NuGet package in order to release this into the marketplace.

**Comment by ejohn20** [comment]
Addressed in release 2.1.0.0
