### ISSUE TITLE
Package version was not found: 2.0.0

### ISSUE THREAD

**Issue by rashhmijain** [pumasecurity/puma-scan#62]
SonarQube.Roslyn.SDK-2.0> RoslynSonarQubePluginGenerator.exe /a:Analyzer2:2.0.0  
Roslyn Analyzer Plugin Generator for SonarQube 2.0.0.0
Maximum supported Roslyn version: 2.9.0.0
Minimum supported SonarQube version: 6.7 (highest version tested against: 7.3-alpha1)
[DEBUG] Parsed NuGet reference. Id: Analyzer2, version: 2.0.0
[DEBUG] Using rules xml file 'rules1.xml'
[DEBUG] Fetching NuGet config files...
[DEBUG] Enabled package sources:
[DEBUG]     https://www.nuget.org/api/v2/, machine-wide: False
[DEBUG]     C:\LocalNuGetFeed, machine-wide: False
[DEBUG]     https://dotnet.myget.org/F/roslyn/api/v3/index.json, machine-wide: False
Attempting to locate package with id 'Analyzer2'
[WARNING] [NuGet] An error occurred while loading packages from 'https://dotnet.myget.org/F/roslyn/api/v3/index.json': The remote server returned an error: (404) Not Found.
[DEBUG] Number of packages located: 1
[DEBUG] Package versions:
  1.0.0 - latest version

Package version was not found: 2.0.0

I have the nupkg package file with the name Analyzer2.2.0.0.nupkg in the same location. If I don't specify the version and run it like-

SonarQube.Roslyn.SDK-2.0> RoslynSonarQubePluginGenerator.exe /a:Analyzer2

it takes the version 1.0.0 as default, and creates jar successfully, but the changes are not reflected.

**Comment by ejohn20** [comment]
Current version is 2.3.0
