### ISSUE TITLE
Invalid Certificate

### ISSUE THREAD

**Issue by nikk1e** [pumasecurity/puma-scan#68]
The certificate used to sign the code when installing via the VSIX is invalid (has expired).

08/02/2021 15:45:36 - 	SignatureState     : InvalidCertificate
08/02/2021 15:45:36 - 	SignedBy           : Puma Security LLC
08/02/2021 15:45:36 - 	Certificate Info   : 
08/02/2021 15:45:36 - 		-------------------------------------------------------
08/02/2021 15:45:36 - 		[Subject]       : CN=Puma Security LLC, O=Puma Security LLC, L=Golden, S=Colorado, C=US
08/02/2021 15:45:36 - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
08/02/2021 15:45:36 - 		[Serial Number] : 01E8A2AF57F12C8D087B5E678DFxxxxx
08/02/2021 15:45:36 - 		[Not Before]    : 02/10/2017 01:00:00
08/02/2021 15:45:36 - 		[Not After]     : 04/12/2020 12:00:00
08/02/2021 15:45:36 - 		[Thumbprint]    : 8EBF2ADFB6C61CF853DFEF81CB27991D2E6D7xxx

08/02/2021 15:45:36 - Signature Details...
08/02/2021 15:45:36 - 	Extension is signed with an invalid certificate
08/02/2021 15:45:36 - 		(NotTimeValid)      : A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.

**Comment by ejohn20** [comment]
Thanks for the heads up. Building a new installer now...

**Comment by ejohn20** [comment]
New release w/ updated code signing certificate: https://marketplace.visualstudio.com/items?itemName=PumaSecurity.PumaScan
