### ISSUE TITLE
2.4.7 release on marketplace.visualstudio but no release nor commits here

### ISSUE THREAD

**Issue by duncancoppedge** [pumasecurity/puma-scan#69]
Visual Studio wants me to update it manually and no commits against this repo since July 2020 makes me a little nervous about what it might contain.
Been an awesome extension so far just every release on marketplace had corresponding commits and release here on github.
Thanks!

**Comment by ejohn20** [comment]
Thanks for the nudge. I just created the release identifying what changed. https://github.com/pumasecurity/puma-scan/releases/tag/2.4.7
