### ISSUE TITLE
Crypto Rules

### ISSUE THREAD

**Issue by curea** [pumasecurity/puma-scan#7]
Weak Hash Algorithms: MD2, MD4 and MD5, SHA1

Weak Crypto Algorithm: DES

Static IV's

Hard-coded Keys

Weak Key Length: Blowfish (< 128), RSA (< 2048)

ECB Mode on a block cipher

**Comment by ejohn20** [comment]
MD5, SHA1, DES, and ECB are covered in this release. Opening separate tickets for the remaining items.
