### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by ChrWeinert** [pumasecurity/puma-scan#72]
Hello,
Puma-Scan for Visual Studio is a great extension to scan for security issues.

After upgrading to VS 2022 the plugin is no longer available.

Can You tell me when the extension comes with VS 2022 support?

Best Regards
Christian Weinert

**Comment by meadisu27** [comment]
Hi Christian - the next release for Puma Scan Professional Edition is slated to occur at the end of this month/early Feb. This release will include support for VS 2022. The Community Edition will receive the VS 2022 shortly after.

**Comment by ChrWeinert** [comment]
Thanks for the information.
I´m looking forward to the release to continue the use of this cool tool!
